[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
[".ohmyzsh-custom/plugins/wezterm/wezterm.sh"]
    type = "file"
    url = "https://github.com/wezterm/wezterm/raw/refs/heads/main/assets/shell-integration/wezterm.sh"
    refreshPeriod = "168h"
